#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonpointer
Version  : 1.9
Release  : 15
URL      : https://pypi.python.org/packages/source/j/jsonpointer/jsonpointer-1.9.tar.gz
Source0  : https://pypi.python.org/packages/source/j/jsonpointer/jsonpointer-1.9.tar.gz
Summary  : Identify specific nodes in a JSON document (RFC 6901)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonpointer-bin
Requires: jsonpointer-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-json-pointer [![Build Status](https://secure.travis-ci.org/stefankoegl/python-json-pointer.png?branch=master)](https://travis-ci.org/stefankoegl/python-json-pointer) [![Coverage Status](https://coveralls.io/repos/stefankoegl/python-json-pointer/badge.png?branch=master)](https://coveralls.io/r/stefankoegl/python-json-pointer?branch=master) ![Downloads](https://pypip.in/d/jsonpointer/badge.png) ![Version](https://pypip.in/v/jsonpointer/badge.png)
===================

%package bin
Summary: bin components for the jsonpointer package.
Group: Binaries

%description bin
bin components for the jsonpointer package.


%package python
Summary: python components for the jsonpointer package.
Group: Default

%description python
python components for the jsonpointer package.


%prep
%setup -q -n jsonpointer-1.9

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
python tests.py
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jsonpointer

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
