#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonpointer
Version  : 2.0
Release  : 37
URL      : https://files.pythonhosted.org/packages/52/e7/246d9ef2366d430f0ce7bdc494ea2df8b49d7a2a41ba51f5655f68cfe85f/jsonpointer-2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/52/e7/246d9ef2366d430f0ce7bdc494ea2df8b49d7a2a41ba51f5655f68cfe85f/jsonpointer-2.0.tar.gz
Summary  : Identify specific nodes in a JSON document (RFC 6901)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonpointer-bin
Requires: jsonpointer-python3
Requires: jsonpointer-license
Requires: jsonpointer-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===================
        
        |PyPI version| |Supported Python versions| |Build Status| |Coverage
        Status|
        
        Resolve JSON Pointers in Python
        -------------------------------
        
        Library to resolve JSON Pointers according to `RFC

%package bin
Summary: bin components for the jsonpointer package.
Group: Binaries
Requires: jsonpointer-license

%description bin
bin components for the jsonpointer package.


%package license
Summary: license components for the jsonpointer package.
Group: Default

%description license
license components for the jsonpointer package.


%package python
Summary: python components for the jsonpointer package.
Group: Default
Requires: jsonpointer-python3

%description python
python components for the jsonpointer package.


%package python3
Summary: python3 components for the jsonpointer package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jsonpointer package.


%prep
%setup -q -n jsonpointer-2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532243411
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python tests.py
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/jsonpointer
cp LICENSE.txt %{buildroot}/usr/share/doc/jsonpointer/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jsonpointer

%files license
%defattr(-,root,root,-)
/usr/share/doc/jsonpointer/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
