#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonpointer
Version  : 1.10
Release  : 29
URL      : http://pypi.debian.net/jsonpointer/jsonpointer-1.10.tar.gz
Source0  : http://pypi.debian.net/jsonpointer/jsonpointer-1.10.tar.gz
Summary  : Identify specific nodes in a JSON document (RFC 6901)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonpointer-bin
Requires: jsonpointer-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===================
        
        Resolve JSON Pointers in Python
        -------------------------------
        
        Library to resolve JSON Pointers according to

%package bin
Summary: bin components for the jsonpointer package.
Group: Binaries

%description bin
bin components for the jsonpointer package.


%package python
Summary: python components for the jsonpointer package.
Group: Default

%description python
python components for the jsonpointer package.


%prep
%setup -q -n jsonpointer-1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503094291
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python tests.py
%install
export SOURCE_DATE_EPOCH=1503094291
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jsonpointer

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
